### ISSUE TITLE
local() is missing a name argument

### ISSUE THREAD

**Issue by mangelozzi** [majodev/google-webfonts-helper#136]
It seems that the `local()` function should a description of the font one is looking for:
<https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face#description>

``` css
/* roboto-regular - latin */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local(''),  /* <-----  notice the empty name/description of the font here */
       url('../fonts/roboto-v29-latin-regular.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
       url('../fonts/roboto-v29-latin-regular.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
}
```
