### ISSUE TITLE
Self Hosted Alternative

### ISSUE THREAD

**Issue by otherwiseGG** [majodev/google-webfonts-helper#159]
Hey!

To avoid Downtime we wanted to host this Instance internally ourselfs and tried to set it up.
Switched Arround in Node Versions and followed Comments as for example in #131 or #48.

Unfortunately, we cannot get it running as it seems to interfere with the State of the Project (Old Dependencies, Newer OS Versions etc.) as we keep on getting error upon error.

Is there some guide somewhere / comment where someone explains on how to Self-Host this internally at the current time and not from like... 7-8 years ago?

Thanks in advance!

**Comment by rponline** [comment]
Oh, it's offline!

Following got me already pretty far:

* download and install node version manager `nvm`
* `nvm install 0.10.44`
* `npm install`
* `npm install -g bower`
* `bower install`
* `npm run start`

the less css compiler doesn't work yet.

I'm trying around right now with ...
* `npm install -g grunt@0.4.5 grunt-cli@1.2.0`
* `grunt build`
* getting the error `FileError: 'font-awesome/less/font-awesome.less' wasn't found in client/app/app.less on line 3, column 1:`

**Comment by lxbdr** [comment]
@rponline thanks for pointing out some of the issues... I spent the last few hours trying to make it work in a docker container but I'm encountering loads of issues

What I got so far:
- You need to have grunt installed and if you are going to use node 0.10.44, you will run into problems with current versions, so I searched for older package versions that were released around the time of the versions referenced in the package.json (mid 2014)
- Same might be true for bower
- Definitely need to fix the `bower.json` before running `bower install` the first time, otherwise it messes up the node_modules folder with modern js that breaks further bower usage
- Before running `grunt serve` client and server files must be built(?) run `grunt build`
-`grunt serve` isn't serving the correct dir (`./public` instead of `./dist/public`)

Not yet resolved:
- Build is failing because a `bootstrap.less` file is apparently missing
- Understanding if and how the environments needs to be configured

My `docker-compose.yml` so far:
```yaml
version: "2"

services:
  node:
    image: "node:0.10.44"
    user: "www-data"
    working_dir: /var/www
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/var/www
    expose:
      - "9000"
    ports:
      - "9000"
      - "8080"
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm install grunt-cli@0.1.13 --save-dev
        npm install bower@1.3.5 --save-dev
        node_modules/bower/bin/bower install
        mkdir -p client/bower_components
        npm run build
        ln -s dist/public public
        npm run serve
```
additions to package.json to make local grunt work with `npm run xxx`

```json
"scripts": {
    "start": "node server/app.js",
    "test": "grunt test",
    "build": "grunt --verbose --force build",
    "serve": "grunt --verbose --force serve",
    "update-webdriver": "node node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager update"
  },
```
