### ISSUE TITLE
Where do I see the version of a font?

### ISSUE THREAD

**Issue by digeomel** [majodev/google-webfonts-helper#93]
I've downloaded OpenSans using your Web app, and I noticed it says that they are version 17.
The question is, where is this version coming from? I searched around on the google fonts website and the github page and all I could find for OpenSans was this:

![image](https://user-images.githubusercontent.com/3295889/72069741-21daa480-32e8-11ea-8afe-442c313d1ca6.png)

There is no mention of the number 17 anywhere.

**Comment by denisbrodbeck** [comment]
If you select the font from [google fonts](https://fonts.google.com/specimen/Open+Sans?query=open+sans&sidebar.open&selection.family=Open+Sans#standard-styles) and select the `Embed` option, you get the this link `<link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">`

Calling the `https://fonts.googleapis.com/css2?family=Open+Sans&display=swap` link in your browser gives you:

```css
/* cyrillic-ext */
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: local('Open Sans Regular'), local('OpenSans-Regular'), url(https://fonts.gstatic.com/s/opensans/v17/mem8YaGs126MiZpBA-UFWJ0bbck.woff2) format('woff2');
  unicode-range: U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F;
}
/* cyrillic */
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: local('Open Sans Regular'), local('OpenSans-Regular'), url(https://fonts.gstatic.com/s/opensans/v17/mem8YaGs126MiZpBA-UFUZ0bbck.woff2) format('woff2');
  unicode-range: U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116;
}
...
```

There you can see the version 17: `https://fonts.gstatic.com/s/opensans/v17`
